AppBundle\Entity\User:
    relations:
        -
            rel: self
            href:
                route: api_users_get_one
                parameters:
                    user: expr(object.getId())
    exclusion_policy: ALL
    access_type: public_method
    properties:
        id:
            expose: true
        username:
            expose: true
        password:
            expose: false
        roles:
            expose: false
