AppBundle\Entity\User:
    relations:
        -
            rel: school
            href:
                route: api_users_get_user_school
                parameters:
                    user: expr(object.getId())
    exclusion_policy: ALL
    access_type: public_method
    properties:
        id:
            expose: true
        username:
            expose: true
