AppBundle\Entity\School:
    relations:
        -
            rel: users
            href:
                route: api_schools_get_school_users
                parameters:
                    school: expr(object.getId())
    exclusion_policy: ALL
    access_type: public_method
    properties:
        id:
            expose: true
        name:
            expose: true
