app_schools_get_one:
    path: /schools/{school}
    methods: [ GET ]
    defaults: { _controller: app.controller.schools:getOneAction }

app_schools_get_all:
    path: /schools/
    methods: [ GET ]
    defaults: { _controller: app.controller.schools:getAllAction }

app_schools_get_related_users:
    path: /schools/{school}/links/users
    methods: [ GET ]
    defaults: { _controller: app.controller.schools:getRelatedUsersAction }
