app_users_get_one:
    path: /users/{user}
    methods: [ GET ]
    defaults: { _controller: app.controller.users:getOneAction }

app_users_get_all:
    path: /users/
    methods: [ GET ]
    defaults: { _controller: app.controller.users:getAllAction }

app_users_get_related_school:
    path: /users/{user}/links/school
    methods: [ GET ]
    defaults: { _controller: app.controller.users:getRelatedSchoolAction }
