parameters:
    api.serializer.json_api.class: ApiBundle\Serializer\JsonApiSerializer
    api.serializer.subscriber.resource_type.class: ApiBundle\Serializer\Subscriber\ResourceTypeSubscriber

services:
    api.serializer.json_api:
        class: %api.serializer.json_api.class%

    api.serializer.subscriber.resource_type:
        class: %api.serializer.subscriber.resource_type.class%
        arguments:
            - %api.serializer.mapping.resource_types%
        tags:
            - { name: jms_serializer.event_subscriber }
