parameters:
    api.controller.users.class: ApiBundle\Controller\UsersController
    api.serializer.json_api.class: ApiBundle\Serializer\JsonApiSerializer
    api.serializer.subscriber.resource_type.class: ApiBundle\Serializer\Subscriber\ResourceTypeSubscriber

services:
    api.controller.users:
        class: %api.controller.users.class%
        arguments:
            - @serializer
            - @api.repository.users

    api.repository.users:
        class: AppBundle\Entity\Repository\UserRepository
        factory_service: doctrine.orm.default_entity_manager
        factory_method: getRepository
        arguments:
            - AppBundle:User

    api.serializer.json_api:
        class: %api.serializer.json_api.class%

    api.serializer.subscriber.resource_type:
        class: %api.serializer.subscriber.resource_type.class%
        arguments:
            -
                AppBundle\Entity\User: users
        tags:
            - { name: jms_serializer.event_subscriber }
