parameters:
    api.controller.users.class: ApiBundle\Controller\UsersController
    api.serializer.json_api.class: ApiBundle\Serializer\JsonApiSerializer
    api.serializer.subscriber.resource_type.class: ApiBundle\Serializer\Subscriber\ResourceTypeSubscriber
    api.serializer.mapping.resource_types: #TODO: Make resource types configurable.
        AppBundle\Entity\User: users
    api.serializer.mapping.links.self:
        AppBundle\Entity\User:
            route: api_users_get_one
            parameters:
                user: expr(object.getId())

services:
    api.controller.users:
        class: %api.controller.users.class%
        arguments:
            - @serializer
            - @api.repository.users

    api.repository.users:
        class: AppBundle\Entity\Repository\UserRepository
        factory_service: doctrine.orm.default_entity_manager
        factory_method: getRepository
        arguments:
            - AppBundle:User

    api.serializer.json_api:
        class: %api.serializer.json_api.class%

    api.serializer.subscriber.resource_type:
        class: %api.serializer.subscriber.resource_type.class%
        arguments:
            - %api.serializer.mapping.resource_types%
        tags:
            - { name: jms_serializer.event_subscriber }
