parameters:
    api.serializer.json_api.class: ApiBundle\Serializer\JsonApiSerializer
    api.serializer.subscriber.resource_type.class: ApiBundle\Serializer\Subscriber\ResourceTypeSubscriber
    api.serializer.mapping.resource_types: {}
#        AppBundle\Entity\User: users
    api.serializer.mapping.links.self: {}
#        AppBundle\Entity\User:
#            route: api_users_get_one
#            parameters:
#                user: expr(object.getId())
#        AppBundle\Entity\School:
#            route: api_schools_get_one
#            parameters:
#                school: expr(object.getId())

services:
    api.serializer.json_api:
        class: %api.serializer.json_api.class%

    api.serializer.subscriber.resource_type:
        class: %api.serializer.subscriber.resource_type.class%
        arguments:
            - %api.serializer.mapping.resource_types%
        tags:
            - { name: jms_serializer.event_subscriber }
