parameters:
    api.controller.users.class: ApiBundle\Controller\UsersController
    api.serializer.json_api.class: ApiBundle\Serializer\JsonApiSerializer

services:
    api.controller.users:
        class: %api.controller.users.class%
        arguments:
            - @serializer
            - @api.repository.users

    api.repository.users:
        class: AppBundle\Entity\Repository\UserRepository
        factory_service: doctrine.orm.default_entity_manager
        factory_method: getRepository
        arguments:
            - AppBundle:User

    api.serializer.json_api:
        class: %api.serializer.json_api.class%
