ApiBundle\Representation\CollectionRepresentation:
    relations:
        -
            rel: self
            href:
                route: api_users_get_all
    exclusion_policy: ALL
    virtual_properties:
        getResources:
            serialized_name: data
            type: array
