ApiBundle\Representation\CollectionRepresentation:
    relations:
        -
            rel: self
            href:
                route: expr(object.getRoute())
    exclusion_policy: ALL
    virtual_properties:
        getResources:
            serialized_name: data
            type: array
